<template>
  <footer
    class="sticky bottom-0 w-full py-4 bg-white border border-b-0 border-gray-100 z-20"
  >
    <UiFooterMenuWrapper>
      <UiFooterMenu
        to="/home/transactions"
        menu-text="Home"
        menu-icon="i-lucide-house"
      />
      <UiFooterMenu
        to="/statistics"
        menu-text="Statistics"
        menu-icon="i-lucide-chart-line"
      />
      <UiFooterMenu
        to="/settings"
        menu-text="Settings"
        menu-icon="i-lucide-user-cog"
      />
    </UiFooterMenuWrapper>
  </footer>
</template>
