<template>
  <footer class="fixed bottom-0 w-full py-4 bg-white border-t border-gray-100">
    <UiFooterMenuWrapper>
      <UiFooterMenu
        to="/home/transactions"
        menu-text="Home"
        menu-icon="i-lucide-house"
      />
      <UiFooterMenu
        to="/statistics"
        menu-text="Statistics"
        menu-icon="i-lucide-chart-line"
      />
      <UiFooterMenu
        to="/settings"
        menu-text="Settings"
        menu-icon="i-lucide-user-cog"
      />
    </UiFooterMenuWrapper>
  </footer>
</template>
